# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [50]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
#from google.colab import files
#uploaded = files.upload()

In [53]:
import numpy as np
import pandas as pd
import io
from sklearn.datasets import load_iris

#df = pd.read_csv(io.StringIO(uploaded['iris.csv'].decode('utf-8')))
#df.head()
#load iris dataset from sklearn
iris = load_iris()
type(iris)


sklearn.utils.Bunch

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [54]:
#create independant feature matrix
X = iris.data
print(len(X))

#create target feature
y = iris.target
print(len(y))

150
150


## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
# Import `train_test_split` from `sklearn.model_selection`
from sklearn.model_selection import train_test_split

# Split the data in train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [56]:
len(y_test)

38

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
from tensorflow.keras.utils import to_categorical

In [0]:
#One-Hot Encoding the output class label
y_train=to_categorical(y_train,3,dtype='int')
y_test=to_categorical(y_test,3,dtype='int')

In [59]:
y_test

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
import tensorflow as tf
from tensorflow.keras import models
from tensorflow.keras.layers import Dense
#Initialize Sequential Graph (model)
model = tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(Dense(4, activation='relu', input_shape=(4,)))
model.add(Dense(4, activation='relu'))
model.add(Dense(3, activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
#Compile the model - add Loss and Gradient Descent optimizer
model.compile(optimizer='sgd', loss='categorical_crossentropy',metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [63]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 15        
Total params: 55
Trainable params: 55
Non-trainable params: 0
_________________________________________________________________


In [0]:
# Number of trainable parameters is 55. There are no non-trainable parameters.

## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [65]:
model.fit(X_train, y_train, epochs=100, validation_data=(X_test,y_test))

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 0s 3ms/sample - loss: 1.5174 - accuracy: 0.3482 - val_loss: 1.3837 - val_accuracy: 0.2895
Epoch 2/100
112/112 [==============================] - 0s 149us/sample - loss: 1.3323 - accuracy: 0.3482 - val_loss: 1.2646 - val_accuracy: 0.2895
Epoch 3/100
112/112 [==============================] - 0s 209us/sample - loss: 1.2352 - accuracy: 0.3482 - val_loss: 1.2039 - val_accuracy: 0.2895
Epoch 4/100
112/112 [==============================] - 0s 156us/sample - loss: 1.1816 - accuracy: 0.3482 - val_loss: 1.1702 - val_accuracy: 0.2895
Epoch 5/100
112/112 [==============================] - 0s 160us/sample - loss: 1.1510 - accuracy: 0.3482 - val_loss: 1.1418 - val_accuracy: 0.2895
Epoch 6/100
112/112 [==============================] - 0s 160us/sample - loss: 1.1259 - accuracy: 0.3482 - val_loss: 1.1277 - val_accuracy: 0.2895
Epoch 7/100
112/112 [==============================] - 0s 156us/sample - lo

## Question 10

### Make predictions
- Predict labels on one row

In [70]:
#printing the predicted values of 0th row
model.predict(X_test[0:1])

array([[0.10825846, 0.3830536 , 0.5086879 ]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [72]:
#printing the actual values of 0th row
y_test[0:1]

array([[0, 1, 0]])

In [74]:
score = model.evaluate(X_test, y_test,verbose=1)

print(score)

38/38 [==============================] - 0s 146us/sample - loss: 0.7620 - accuracy: 0.7105
[0.761971094106373, 0.7105263]


In [75]:
model.metrics_names

['loss', 'accuracy']



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [77]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [79]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

Saving prices.csv to prices.csv


In [119]:
import numpy as np
import pandas as pd

df = pd.read_csv('prices.csv')
df.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
date      851264 non-null object
symbol    851264 non-null object
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB


## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
df.drop(['date','symbol'],axis=1,inplace=True)

In [122]:
df.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [123]:
#printing the shape of df before 
print(df.shape)
stock_df = df[0:1000]
print(stock_df.shape)
stock_df.head()

(851264, 5)
(1000, 5)


open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [124]:
# Assigning independant features to X
X = stock_df
X = X.drop('volume',axis=1)
print(X.head())

y= stock_df['volume']
print(y.head())

         open       close         low        high
0  123.430000  125.839996  122.309998  126.250000
1  125.239998  119.980003  119.940002  125.540001
2  116.379997  114.949997  114.930000  119.739998
3  115.480003  116.620003  113.500000  117.440002
4  117.010002  114.970001  114.089996  117.330002
0    2163600.0
1    2386400.0
2    2489500.0
3    2006300.0
4    1408600.0
Name: volume, dtype: float64


In [125]:
 # Normalize label column by dividing it with 1000000
 y = y/(1000000)
 print(y)

0       2.1636
1       2.3864
2       2.4895
3       2.0063
4       1.4086
        ...   
995     2.1332
996     1.9824
997    37.1528
998     6.5686
999     5.6043
Name: volume, Length: 1000, dtype: float64


## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [126]:
#Converting features and labels to numpy array and converting their datatype to float32
X_arr = X.to_numpy().astype(np.float32)
y_arr = y.to_numpy().astype(np.float32)

print(type(X_arr))
print(type(y_arr))

print(X_arr.dtype)
print(y_arr.dtype)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
float32
float32


## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
X_arr_norm = tf.math.l2_normalize(
    X_arr,
    axis=None,
    epsilon=1e-12,
    name=None
)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [128]:
W = tf.zeros(shape=(4, 1)) 
b = tf.zeros(shape=(1))

print(W)
print(b)

tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]], shape=(4, 1), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)


## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function 
def prediction(X, W, b):     
  y_pred = tf.add(tf.matmul(X, W), b)     
  return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
 @tf.function
 def loss(y_actual, y_pred):
   diff = y_actual - y_pred   
   sqr = tf.square(diff)     
   mse = tf.reduce_mean(sqr)     
   return mse 

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(X, y_actual, w, b, learning_rate=0.01):
  # Record mathematical operations on 'tape' to calculate loss     
  with tf.GradientTape() as t:         
    t.watch([w,b])         
    current_prediction = prediction(X, w, b)         
    current_loss = loss(y_actual, current_prediction)          
  # Calculate Gradients for Loss with respect to Weights and Bias     
  dw, db = t.gradient(current_loss,[w, b])          
  # Update Weights and Bias     
  w = w - learning_rate * dw     
  b = b - learning_rate * db          
  return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [132]:
#print(X_arr_norm)
for i in range(100):         
    W, b = train(X_arr_norm,y_arr, W, b)  
    print('Current Training Loss on iteration', i, loss(y_arr, prediction(X_arr_norm, W, b)).numpy())

Current Training Loss on iteration 0 236.16759
Current Training Loss on iteration 1 235.09299
Current Training Loss on iteration 2 234.06102
Current Training Loss on iteration 3 233.06998
Current Training Loss on iteration 4 232.11781
Current Training Loss on iteration 5 231.20381
Current Training Loss on iteration 6 230.32585
Current Training Loss on iteration 7 229.48265
Current Training Loss on iteration 8 228.67297
Current Training Loss on iteration 9 227.89539
Current Training Loss on iteration 10 227.14832
Current Training Loss on iteration 11 226.43114
Current Training Loss on iteration 12 225.74234
Current Training Loss on iteration 13 225.0808
Current Training Loss on iteration 14 224.44553
Current Training Loss on iteration 15 223.835
Current Training Loss on iteration 16 223.24931
Current Training Loss on iteration 17 222.68655
Current Training Loss on iteration 18 222.14595
Current Training Loss on iteration 19 221.62688
Current Training Loss on iteration 20 221.12842
Curre

### Observe values of Weight
- Print the updated values

In [133]:
print(W)

tf.Tensor(
[[0.0547828 ]
 [0.05488191]
 [0.05422735]
 [0.05533117]], shape=(4, 1), dtype=float32)


### Observe values of Bias
- Print the updated values

In [134]:
print(b)

tf.Tensor([4.607657], shape=(1,), dtype=float32)
